- aur: name=notion-app
- aur: name=wavebox
- aur: name=vpn-slice-git
- aur: name=direnv
- aur: name=remmina-plugin-rdesktop
- aur: name=google-chrome
- aur: name=peco
- aur: name=fzf-git
- aur: name=wavebox
- aur: name=zoxide-bin

- name: Install base packages
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: yes
  become_user: root
  become_method: sudo
  loop:
    - openconnect
    - dnsmasq
    - networkmanager-openconnect
    - rdesktop
    - remmina
    - python-poetry
    - yubioath-desktop
    - ccid
    - cups
    - hplip
    - httpie
    - python-pip
    - graphviz

- name: Enable a cups
  ansible.builtin.systemd:
    name: cups
    state: started
    enabled: yes
  become: yes
  become_user: root
  become_method: sudo
