- name: Install base packages
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: yes
  become_user: root
  become_method: sudo
  loop:
    - kubectl
    - kubectx

- aur: name=lens-bin
- aur: name=origin-client
- aur: name=k9s
- aur: name=krew-bin
